# NumPy

**Advanced Analytics using Statistics - PG-DBDA**

This notebook covers all essential NumPy concepts required for AI/ML engineering, aligned with the DBDA curriculum.

## Table of Contents
1. Introduction & Setup
2. Array Creation & Basics
3. Array Indexing & Slicing
4. Array Manipulation & Reshaping
5. Mathematical Operations
6. Statistical Operations (Descriptive Statistics)
7. Random Number Generation & Probability Distributions
8. Linear Algebra Operations
9. Advanced Topics (Broadcasting, Vectorization)
10. Real-world Applications for Analytics

## 1. Introduction & Setup

NumPy (Numerical Python) is the fundamental package for scientific computing in Python. It provides:
- High-performance multidimensional array objects
- Tools for working with arrays
- Mathematical functions
- Linear algebra operations
- Random number generation

**Why NumPy for AI/ML?**
- Fast vectorized operations (50-100x faster than pure Python)
- Memory efficient
- Foundation for pandas, scikit-learn, TensorFlow, PyTorch
- Essential for data preprocessing, feature engineering, and statistical analysis

In [11]:
# Install NumPy (if not already installed)
# !pip install numpy

# Import NumPy
import numpy as np

# Check version
print(f"NumPy Version: {np.__version__}")

# NumPy configuration
np.set_printoptions(precision=4, suppress=True)  # Set display options
print("NumPy imported successfully!")

NumPy Version: 2.3.4
NumPy imported successfully!


## 2. Array Creation & Basics

NumPy arrays (ndarrays) are the core data structure in NumPy. They are:
- Homogeneous (all elements same type)
- Fixed size at creation
- Multi-dimensional
- Much faster than Python lists for numerical operations

### 2.1 Creating Arrays from Lists and Tuples

In [12]:
# 1D Array from list
arr_1d = np.array([1, 2, 3, 4, 5])
print("1D Array:", arr_1d)
print("Type:", type(arr_1d))
print("Data type:", arr_1d.dtype)
print("Shape:", arr_1d.shape)
print("Dimensions:", arr_1d.ndim)
print()

# 2D Array from nested list
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
print("2D Array:\n", arr_2d)
print("Shape:", arr_2d.shape)
print("Size (total elements):", arr_2d.size)
print()

# 3D Array
arr_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print("3D Array:\n", arr_3d)
print("Shape:", arr_3d.shape)
print("Dimensions:", arr_3d.ndim)

1D Array: [1 2 3 4 5]
Type: <class 'numpy.ndarray'>
Data type: int64
Shape: (5,)
Dimensions: 1

2D Array:
 [[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Size (total elements): 6

3D Array:
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
Shape: (2, 2, 2)
Dimensions: 3


### 2.2 Built-in Array Creation Functions

In [13]:
# Zeros array
zeros = np.zeros((3, 4))
print("Zeros array (3x4):\n", zeros)
print()

# Ones array
ones = np.ones((2, 3, 4))
print("Ones array (2x3x4) - shape:", ones.shape)
print()

# Array filled with a constant
full = np.full((2, 3), 7)
print("Array filled with 7:\n", full)
print()

# Identity matrix (important for linear algebra)
identity = np.eye(4)
print("Identity matrix (4x4):\n", identity)
print()

# Array with range of values
arange_arr = np.arange(0, 10, 2)  # start, stop, step
print("Array with arange (0 to 10, step 2):", arange_arr)
print()

# Linearly spaced array (important for plotting, simulations)
linspace_arr = np.linspace(0, 1, 5)  # start, stop, num_points
print("Linearly spaced array (0 to 1, 5 points):", linspace_arr)
print()

# Empty array (uninitialized - faster but contains garbage values)
empty = np.empty((2, 2))
print("Empty array:\n", empty)

Zeros array (3x4):
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

Ones array (2x3x4) - shape: (2, 3, 4)

Array filled with 7:
 [[7 7 7]
 [7 7 7]]

Identity matrix (4x4):
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

Array with arange (0 to 10, step 2): [0 2 4 6 8]

Linearly spaced array (0 to 1, 5 points): [0.   0.25 0.5  0.75 1.  ]

Empty array:
 [[0.25 0.5 ]
 [0.75 1.  ]]


### 2.3 Data Types in NumPy

NumPy supports various data types for memory efficiency and precision.

In [14]:
# Integer types
int_arr = np.array([1, 2, 3], dtype=np.int32)
print("Int32 array:", int_arr, "| dtype:", int_arr.dtype)

# Float types
float_arr = np.array([1.5, 2.7, 3.9], dtype=np.float64)
print("Float64 array:", float_arr, "| dtype:", float_arr.dtype)

# Boolean
bool_arr = np.array([True, False, True], dtype=bool)
print("Boolean array:", bool_arr, "| dtype:", bool_arr.dtype)

# Complex numbers
complex_arr = np.array([1+2j, 3+4j])
print("Complex array:", complex_arr, "| dtype:", complex_arr.dtype)

# Type conversion
arr = np.array([1.7, 2.3, 3.9])
int_converted = arr.astype(np.int32)
print("\nOriginal:", arr)
print("Converted to int:", int_converted)

Int32 array: [1 2 3] | dtype: int32
Float64 array: [1.5 2.7 3.9] | dtype: float64
Boolean array: [ True False  True] | dtype: bool
Complex array: [1.+2.j 3.+4.j] | dtype: complex128

Original: [1.7 2.3 3.9]
Converted to int: [1 2 3]


## 3. Array Indexing & Slicing

Accessing and modifying array elements efficiently.

In [15]:
# 1D Indexing
arr = np.array([10, 20, 30, 40, 50])
print("Array:", arr)
print("First element:", arr[0])
print("Last element:", arr[-1])
print("Slice [1:4]:", arr[1:4])
print("Every 2nd element:", arr[::2])
print()

# 2D Indexing
arr_2d = np.array([[1, 2, 3, 4],
                   [5, 6, 7, 8],
                   [9, 10, 11, 12]])
print("2D Array:\n", arr_2d)
print("Element at [1, 2]:", arr_2d[1, 2])
print("First row:", arr_2d[0])
print("Second column:", arr_2d[:, 1])
print("Subarray [0:2, 1:3]:\n", arr_2d[0:2, 1:3])
print()

# Boolean indexing (very important for data filtering)
arr = np.array([1, 2, 3, 4, 5, 6])
mask = arr > 3
print("Array:", arr)
print("Mask (arr > 3):", mask)
print("Elements > 3:", arr[mask])
print("Elements divisible by 2:", arr[arr % 2 == 0])
print()

# Fancy indexing (using arrays as indices)
arr = np.array([10, 20, 30, 40, 50])
indices = np.array([0, 2, 4])
print("Array:", arr)
print("Elements at indices [0, 2, 4]:", arr[indices])

Array: [10 20 30 40 50]
First element: 10
Last element: 50
Slice [1:4]: [20 30 40]
Every 2nd element: [10 30 50]

2D Array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Element at [1, 2]: 7
First row: [1 2 3 4]
Second column: [ 2  6 10]
Subarray [0:2, 1:3]:
 [[2 3]
 [6 7]]

Array: [1 2 3 4 5 6]
Mask (arr > 3): [False False False  True  True  True]
Elements > 3: [4 5 6]
Elements divisible by 2: [2 4 6]

Array: [10 20 30 40 50]
Elements at indices [0, 2, 4]: [10 30 50]


## 4. Array Manipulation & Reshaping

Essential operations for data preprocessing and model input preparation.

In [16]:
# Reshaping arrays
arr = np.arange(12)
print("Original 1D array:", arr)
print()

# Reshape to 2D
arr_2d = arr.reshape(3, 4)
print("Reshaped to (3, 4):\n", arr_2d)
print()

# Reshape to 3D
arr_3d = arr.reshape(2, 3, 2)
print("Reshaped to (2, 3, 2):\n", arr_3d)
print()

# Flatten array
flattened = arr_2d.flatten()
print("Flattened:", flattened)
print()

# Ravel (flatten without copying - faster)
raveled = arr_2d.ravel()
print("Raveled:", raveled)
print()

# Transpose
arr = np.array([[1, 2, 3], [4, 5, 6]])
print("Original:\n", arr)
print("Transposed:\n", arr.T)
print()

# Adding/removing dimensions
arr = np.array([1, 2, 3])
print("Original shape:", arr.shape)
arr_newaxis = arr[np.newaxis, :]
print("After np.newaxis:", arr_newaxis.shape)
arr_expand = np.expand_dims(arr, axis=0)
print("After expand_dims:", arr_expand.shape)
print()

# Squeeze - remove single-dimensional entries
arr = np.array([[[1, 2, 3]]])
print("Original shape:", arr.shape)
squeezed = np.squeeze(arr)
print("After squeeze:", squeezed.shape, "->", squeezed)

Original 1D array: [ 0  1  2  3  4  5  6  7  8  9 10 11]

Reshaped to (3, 4):
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

Reshaped to (2, 3, 2):
 [[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]]

Flattened: [ 0  1  2  3  4  5  6  7  8  9 10 11]

Raveled: [ 0  1  2  3  4  5  6  7  8  9 10 11]

Original:
 [[1 2 3]
 [4 5 6]]
Transposed:
 [[1 4]
 [2 5]
 [3 6]]

Original shape: (3,)
After np.newaxis: (1, 3)
After expand_dims: (1, 3)

Original shape: (1, 1, 3)
After squeeze: (3,) -> [1 2 3]


In [17]:
# Concatenation
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])

# Vertical stack (along rows)
vstack = np.vstack([arr1, arr2])
print("Vertical stack:\n", vstack)
print()

# Horizontal stack (along columns)
hstack = np.hstack([arr1, arr2])
print("Horizontal stack:\n", hstack)
print()

# Concatenate along specific axis
concat_axis0 = np.concatenate([arr1, arr2], axis=0)
concat_axis1 = np.concatenate([arr1, arr2], axis=1)
print("Concatenate axis=0:\n", concat_axis0)
print("Concatenate axis=1:\n", concat_axis1)
print()

# Splitting arrays
arr = np.arange(16).reshape(4, 4)
print("Original array:\n", arr)

# Split into 2 subarrays
split_arrays = np.split(arr, 2, axis=0)
print("\nSplit into 2 parts:")
for i, sub in enumerate(split_arrays):
    print(f"Part {i+1}:\n", sub)

Vertical stack:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]

Horizontal stack:
 [[1 2 5 6]
 [3 4 7 8]]

Concatenate axis=0:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]
Concatenate axis=1:
 [[1 2 5 6]
 [3 4 7 8]]

Original array:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

Split into 2 parts:
Part 1:
 [[0 1 2 3]
 [4 5 6 7]]
Part 2:
 [[ 8  9 10 11]
 [12 13 14 15]]


## 5. Mathematical Operations

NumPy provides efficient element-wise and matrix operations.

In [18]:
# Element-wise operations (vectorized - VERY FAST!)
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([10, 20, 30, 40])

print("arr1:", arr1)
print("arr2:", arr2)
print()

print("Addition:", arr1 + arr2)
print("Subtraction:", arr1 - arr2)
print("Multiplication:", arr1 * arr2)
print("Division:", arr1 / arr2)
print("Power:", arr1 ** 2)
print("Square root:", np.sqrt(arr1))
print("Exponential:", np.exp(arr1))
print("Logarithm:", np.log(arr1))
print()

# Aggregation functions
arr = np.array([[1, 2, 3], [4, 5, 6]])
print("Array:\n", arr)
print("Sum:", np.sum(arr))
print("Sum along axis 0 (columns):", np.sum(arr, axis=0))
print("Sum along axis 1 (rows):", np.sum(arr, axis=1))
print("Mean:", np.mean(arr))
print("Min:", np.min(arr))
print("Max:", np.max(arr))
print("Product:", np.prod(arr))
print()

# Cumulative operations
arr = np.array([1, 2, 3, 4, 5])
print("Array:", arr)
print("Cumulative sum:", np.cumsum(arr))
print("Cumulative product:", np.cumprod(arr))

arr1: [1 2 3 4]
arr2: [10 20 30 40]

Addition: [11 22 33 44]
Subtraction: [ -9 -18 -27 -36]
Multiplication: [ 10  40  90 160]
Division: [0.1 0.1 0.1 0.1]
Power: [ 1  4  9 16]
Square root: [1.     1.4142 1.7321 2.    ]
Exponential: [ 2.7183  7.3891 20.0855 54.5982]
Logarithm: [0.     0.6931 1.0986 1.3863]

Array:
 [[1 2 3]
 [4 5 6]]
Sum: 21
Sum along axis 0 (columns): [5 7 9]
Sum along axis 1 (rows): [ 6 15]
Mean: 3.5
Min: 1
Max: 6
Product: 720

Array: [1 2 3 4 5]
Cumulative sum: [ 1  3  6 10 15]
Cumulative product: [  1   2   6  24 120]


## 6. Statistical Operations (Critical for Data Analytics)

NumPy provides comprehensive statistical functions essential for the DBDA curriculum.

In [19]:
# Sample data
data = np.array([23, 45, 12, 67, 34, 89, 23, 56, 78, 90, 12, 45, 67, 23])
print("Data:", data)
print()

# Measures of Central Tendency
print("=== Central Tendency ===")
print(f"Mean: {np.mean(data):.2f}")
print(f"Median: {np.median(data):.2f}")
# Mode (using scipy or manual calculation)
from scipy import stats as scipy_stats
mode_result = scipy_stats.mode(data, keepdims=True)
print(f"Mode: {mode_result.mode[0]}")
print()

# Measures of Dispersion
print("=== Dispersion ===")
print(f"Variance: {np.var(data):.2f}")
print(f"Standard Deviation: {np.std(data):.2f}")
print(f"Range: {np.ptp(data)}")  # peak-to-peak (max - min)
print(f"Min: {np.min(data)}")
print(f"Max: {np.max(data)}")
print()

# Quartiles and Percentiles
print("=== Quartiles & Percentiles ===")
print(f"25th Percentile (Q1): {np.percentile(data, 25):.2f}")
print(f"50th Percentile (Q2/Median): {np.percentile(data, 50):.2f}")
print(f"75th Percentile (Q3): {np.percentile(data, 75):.2f}")

q1 = np.percentile(data, 25)
q3 = np.percentile(data, 75)
iqr = q3 - q1
print(f"Interquartile Range (IQR): {iqr:.2f}")
print()

# Coefficient of Variation
cv = (np.std(data) / np.mean(data)) * 100
print(f"Coefficient of Variation: {cv:.2f}%")

Data: [23 45 12 67 34 89 23 56 78 90 12 45 67 23]

=== Central Tendency ===
Mean: 47.43
Median: 45.00
Mode: 23

=== Dispersion ===
Variance: 700.53
Standard Deviation: 26.47
Range: 78
Min: 12
Max: 90

=== Quartiles & Percentiles ===
25th Percentile (Q1): 23.00
50th Percentile (Q2/Median): 45.00
75th Percentile (Q3): 67.00
Interquartile Range (IQR): 44.00

Coefficient of Variation: 55.81%


In [20]:
# Correlation and Covariance (Session 5 & 6 from curriculum)
print("=== Correlation & Covariance ===")

# Two variables
x = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
y = np.array([2, 4, 5, 4, 5, 7, 8, 9, 10, 11])

# Covariance matrix
cov_matrix = np.cov(x, y)
print("Covariance Matrix:")
print(cov_matrix)
print(f"Covariance between x and y: {cov_matrix[0, 1]:.2f}")
print()

# Correlation coefficient (Pearson)
corr_matrix = np.corrcoef(x, y)
print("Correlation Matrix:")
print(corr_matrix)
print(f"Correlation coefficient: {corr_matrix[0, 1]:.4f}")
print()

# Interpretation
corr = corr_matrix[0, 1]
if corr > 0.7:
    print("Strong positive correlation")
elif corr > 0.3:
    print("Moderate positive correlation")
elif corr > -0.3:
    print("Weak or no correlation")
elif corr > -0.7:
    print("Moderate negative correlation")
else:
    print("Strong negative correlation")

=== Correlation & Covariance ===
Covariance Matrix:
[[9.1667 8.7222]
 [8.7222 8.7222]]
Covariance between x and y: 8.72

Correlation Matrix:
[[1.     0.9755]
 [0.9755 1.    ]]
Correlation coefficient: 0.9755

Strong positive correlation


In [21]:
# Outlier Detection (Session 5 & 6)
print("=== Outlier Detection ===")

data = np.array([12, 15, 14, 13, 16, 14, 15, 100, 13, 14, 12, 15])  # 100 is an outlier
print("Data:", data)
print()

# Method 1: Using IQR (Interquartile Range)
q1 = np.percentile(data, 25)
q3 = np.percentile(data, 75)
iqr = q3 - q1

lower_bound = q1 - 1.5 * iqr
upper_bound = q3 + 1.5 * iqr

outliers_iqr = data[(data < lower_bound) | (data > upper_bound)]
clean_data_iqr = data[(data >= lower_bound) & (data <= upper_bound)]

print(f"Q1: {q1}, Q3: {q3}, IQR: {iqr}")
print(f"Bounds: [{lower_bound:.2f}, {upper_bound:.2f}]")
print(f"Outliers (IQR method): {outliers_iqr}")
print(f"Clean data: {clean_data_iqr}")
print()

# Method 2: Using Z-score
mean = np.mean(data)
std = np.std(data)
z_scores = np.abs((data - mean) / std)
threshold = 3  # typically 2 or 3

outliers_zscore = data[z_scores > threshold]
print(f"Mean: {mean:.2f}, Std: {std:.2f}")
print(f"Outliers (Z-score > {threshold}): {outliers_zscore}")

=== Outlier Detection ===
Data: [ 12  15  14  13  16  14  15 100  13  14  12  15]

Q1: 13.0, Q3: 15.0, IQR: 2.0
Bounds: [10.00, 18.00]
Outliers (IQR method): [100]
Clean data: [12 15 14 13 16 14 15 13 14 12 15]

Mean: 21.08, Std: 23.82
Outliers (Z-score > 3): [100]


## 7. Random Number Generation & Probability Distributions

Essential for simulations, sampling, and understanding probability distributions (Sessions 7 & 8).

In [22]:
# Set random seed for reproducibility
np.random.seed(42)

# Basic random number generation
print("=== Basic Random Numbers ===")
random_float = np.random.rand()  # Single random float [0, 1)
print(f"Single random float: {random_float:.4f}")

random_array = np.random.rand(3, 3)  # 3x3 array of random floats
print("3x3 random array:\n", random_array)
print()

random_ints = np.random.randint(1, 100, size=10)  # Random integers
print("Random integers (1-100):", random_ints)
print()

# Normal distribution (Gaussian) - VERY IMPORTANT for ML
print("=== Normal Distribution ===")
normal_data = np.random.normal(loc=50, scale=10, size=1000)  # mean=50, std=10
print(f"Mean: {np.mean(normal_data):.2f}")
print(f"Std: {np.std(normal_data):.2f}")
print(f"Sample values: {normal_data[:10]}")
print()

# Uniform distribution
print("=== Uniform Distribution ===")
uniform_data = np.random.uniform(low=0, high=10, size=100)
print(f"Min: {np.min(uniform_data):.2f}, Max: {np.max(uniform_data):.2f}")
print(f"Mean: {np.mean(uniform_data):.2f}")
print()

# Exponential distribution
print("=== Exponential Distribution ===")
exponential_data = np.random.exponential(scale=2.0, size=100)
print(f"Mean: {np.mean(exponential_data):.2f}")
print()

# Binomial distribution (discrete)
print("=== Binomial Distribution ===")
# n trials, p probability of success
binomial_data = np.random.binomial(n=10, p=0.5, size=100)
print(f"Sample (10 coin flips, each 100 times): {binomial_data[:10]}")
print(f"Mean: {np.mean(binomial_data):.2f}")
print()

# Poisson distribution (discrete)
print("=== Poisson Distribution ===")
poisson_data = np.random.poisson(lam=3, size=100)  # lambda = 3
print(f"Sample: {poisson_data[:10]}")
print(f"Mean: {np.mean(poisson_data):.2f}")

=== Basic Random Numbers ===
Single random float: 0.3745
3x3 random array:
 [[0.9507 0.732  0.5987]
 [0.156  0.156  0.0581]
 [0.8662 0.6011 0.7081]]

Random integers (1-100): [22 53  2 88 30 38  2 64 60 21]

=== Normal Distribution ===
Mean: 50.38
Std: 10.32
Sample values: [64.6238 65.3871 25.6089 56.0344 47.4896 48.3613 35.2367 64.8698 49.7554
 53.5555]

=== Uniform Distribution ===
Min: 0.09, Max: 9.92
Mean: 5.09

=== Exponential Distribution ===
Mean: 2.00

=== Binomial Distribution ===
Sample (10 coin flips, each 100 times): [5 5 5 5 5 2 5 3 6 6]
Mean: 5.00

=== Poisson Distribution ===
Sample: [3 5 3 3 2 4 2 4 2 3]
Mean: 3.08


In [23]:
# Sampling techniques (Session 11 & 12)
print("=== Sampling Techniques ===")

population = np.arange(1, 101)  # Population of 100 elements
print(f"Population size: {len(population)}")
print()

# Simple random sampling
sample = np.random.choice(population, size=10, replace=False)
print(f"Simple random sample (n=10): {sample}")
print()

# Sampling with replacement
sample_with_replacement = np.random.choice(population, size=10, replace=True)
print(f"Sample with replacement: {sample_with_replacement}")
print()

# Shuffling (useful for train/test split)
shuffled = population.copy()
np.random.shuffle(shuffled)
print(f"Shuffled population (first 10): {shuffled[:10]}")

=== Sampling Techniques ===
Population size: 100

Simple random sample (n=10): [ 9 27 51 67 95 62 76 65 87 11]

Sample with replacement: [49 64 32  7 21 20 26 68 86 15]

Shuffled population (first 10): [68 35 17 49 90 91 59 31 65 61]


## 8. Linear Algebra Operations

Critical for machine learning algorithms (regression, neural networks, PCA, etc.).

In [24]:
# Matrix multiplication
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

print("Matrix A:\n", A)
print("Matrix B:\n", B)
print()

# Dot product (matrix multiplication)
dot_product = np.dot(A, B)
print("A @ B (dot product):\n", dot_product)
print()

# Alternative syntax
matmul_result = A @ B
print("A @ B (using @ operator):\n", matmul_result)
print()

# Element-wise multiplication
element_wise = A * B
print("Element-wise multiplication:\n", element_wise)
print()

# Matrix transpose
print("Transpose of A:\n", A.T)
print()

# Matrix determinant
det = np.linalg.det(A)
print(f"Determinant of A: {det:.2f}")
print()

# Matrix inverse
inv_A = np.linalg.inv(A)
print("Inverse of A:\n", inv_A)
print()

# Verify: A @ A_inv = I
identity_check = A @ inv_A
print("A @ A_inv (should be identity):\n", identity_check)
print()

# Eigenvalues and eigenvectors (important for PCA)
eigenvalues, eigenvectors = np.linalg.eig(A)
print("Eigenvalues:", eigenvalues)
print("Eigenvectors:\n", eigenvectors)
print()

# Solving linear equations: Ax = b
b = np.array([1, 2])
x = np.linalg.solve(A, b)
print("Solution to Ax = b:", x)
print("Verification (Ax):", A @ x)

Matrix A:
 [[1 2]
 [3 4]]
Matrix B:
 [[5 6]
 [7 8]]

A @ B (dot product):
 [[19 22]
 [43 50]]

A @ B (using @ operator):
 [[19 22]
 [43 50]]

Element-wise multiplication:
 [[ 5 12]
 [21 32]]

Transpose of A:
 [[1 3]
 [2 4]]

Determinant of A: -2.00

Inverse of A:
 [[-2.   1. ]
 [ 1.5 -0.5]]

A @ A_inv (should be identity):
 [[1. 0.]
 [0. 1.]]

Eigenvalues: [-0.3723  5.3723]
Eigenvectors:
 [[-0.8246 -0.416 ]
 [ 0.5658 -0.9094]]

Solution to Ax = b: [0.  0.5]
Verification (Ax): [1. 2.]


## 9. Advanced Topics - Broadcasting & Vectorization

Broadcasting allows NumPy to work with arrays of different shapes efficiently.

In [25]:
# Broadcasting example 1: Scalar + Array
arr = np.array([1, 2, 3, 4])
result = arr + 10
print("Array:", arr)
print("Array + 10:", result)
print()

# Broadcasting example 2: 1D + 2D
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
arr_1d = np.array([10, 20, 30])
result = arr_2d + arr_1d
print("2D array:\n", arr_2d)
print("1D array:", arr_1d)
print("Result (broadcasting):\n", result)
print()

# Broadcasting example 3: Column vector + Row vector
col = np.array([[1], [2], [3]])
row = np.array([10, 20, 30])
result = col + row
print("Column vector:\n", col)
print("Row vector:", row)
print("Result (outer addition):\n", result)
print()

# Normalization using broadcasting (important for ML preprocessing)
data = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("Original data:\n", data)

# Mean normalization
mean = np.mean(data, axis=0)
std = np.std(data, axis=0)
normalized = (data - mean) / std
print("Normalized data (standardization):\n", normalized)
print("Mean after normalization:", np.mean(normalized, axis=0))
print("Std after normalization:", np.std(normalized, axis=0))

Array: [1 2 3 4]
Array + 10: [11 12 13 14]

2D array:
 [[1 2 3]
 [4 5 6]]
1D array: [10 20 30]
Result (broadcasting):
 [[11 22 33]
 [14 25 36]]

Column vector:
 [[1]
 [2]
 [3]]
Row vector: [10 20 30]
Result (outer addition):
 [[11 21 31]
 [12 22 32]
 [13 23 33]]

Original data:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Normalized data (standardization):
 [[-1.2247 -1.2247 -1.2247]
 [ 0.      0.      0.    ]
 [ 1.2247  1.2247  1.2247]]
Mean after normalization: [0. 0. 0.]
Std after normalization: [1. 1. 1.]


In [26]:
# Vectorization - Why it matters
import time

# Slow way (Python loop)
n = 1000000
python_array = list(range(n))

start = time.time()
result_loop = [x ** 2 for x in python_array]
loop_time = time.time() - start

# Fast way (NumPy vectorization)
numpy_array = np.arange(n)

start = time.time()
result_vectorized = numpy_array ** 2
vectorized_time = time.time() - start

print(f"Loop time: {loop_time:.4f} seconds")
print(f"Vectorized time: {vectorized_time:.4f} seconds")
print(f"Speedup: {loop_time / vectorized_time:.2f}x faster!")
print()

# Vectorized operations for conditional logic
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# Using np.where (vectorized if-else)
result = np.where(arr > 5, arr * 2, arr)
print("Array:", arr)
print("Double if > 5, else keep:", result)

Loop time: 0.0303 seconds
Vectorized time: 0.0011 seconds
Speedup: 28.05x faster!

Array: [ 1  2  3  4  5  6  7  8  9 10]
Double if > 5, else keep: [ 1  2  3  4  5 12 14 16 18 20]


## 10. Real-World Applications for AI/ML

Practical examples demonstrating NumPy in data analytics workflows.

### 10.1 Simple Linear Regression from Scratch

In [27]:
# Generate sample data
np.random.seed(42)
X = np.linspace(0, 10, 50)
y = 2.5 * X + 1 + np.random.normal(0, 2, 50)  # y = 2.5x + 1 + noise

print("Sample data:")
print(f"X: {X[:5]}")
print(f"y: {y[:5]}")
print()

# Calculate regression coefficients using linear algebra
# Formula: beta = (X^T X)^(-1) X^T y
# Add intercept term (column of ones)
X_with_intercept = np.column_stack([np.ones(len(X)), X])

# Calculate coefficients
beta = np.linalg.inv(X_with_intercept.T @ X_with_intercept) @ X_with_intercept.T @ y

intercept, slope = beta
print(f"Regression equation: y = {slope:.2f}x + {intercept:.2f}")
print(f"True equation: y = 2.5x + 1")
print()

# Make predictions
y_pred = X_with_intercept @ beta

# Calculate R-squared
ss_total = np.sum((y - np.mean(y)) ** 2)
ss_residual = np.sum((y - y_pred) ** 2)
r_squared = 1 - (ss_residual / ss_total)

print(f"R-squared: {r_squared:.4f}")
print(f"Mean Squared Error: {np.mean((y - y_pred) ** 2):.4f}")

Sample data:
X: [0.     0.2041 0.4082 0.6122 0.8163]
y: [1.9934 1.2337 3.3158 5.5767 2.5725]

Regression equation: y = 2.38x + 1.13
True equation: y = 2.5x + 1

R-squared: 0.9372
Mean Squared Error: 3.3006


### 10.2 K-Means Clustering from Scratch

In [28]:
# Generate clustered data
np.random.seed(42)
cluster1 = np.random.randn(50, 2) + np.array([2, 2])
cluster2 = np.random.randn(50, 2) + np.array([8, 8])
cluster3 = np.random.randn(50, 2) + np.array([2, 8])
data = np.vstack([cluster1, cluster2, cluster3])

print(f"Data shape: {data.shape}")
print(f"Sample points:\n{data[:3]}")
print()

# Simple K-Means implementation
def kmeans(X, k, max_iters=100):
    # Randomly initialize centroids
    centroids = X[np.random.choice(X.shape[0], k, replace=False)]
    
    for _ in range(max_iters):
        # Assign points to nearest centroid
        distances = np.sqrt(((X - centroids[:, np.newaxis])**2).sum(axis=2))
        labels = np.argmin(distances, axis=0)
        
        # Update centroids
        new_centroids = np.array([X[labels == i].mean(axis=0) for i in range(k)])
        
        # Check convergence
        if np.allclose(centroids, new_centroids):
            break
        centroids = new_centroids
    
    return labels, centroids

# Run K-Means
k = 3
labels, centroids = kmeans(data, k)

print(f"Final centroids:\n{centroids}")
print(f"Cluster assignments: {labels[:10]}...")
print(f"Cluster sizes: {np.bincount(labels)}")

Data shape: (150, 2)
Sample points:
[[2.4967 1.8617]
 [2.6477 3.523 ]
 [1.7658 1.7659]]

Final centroids:
[[1.8643 1.928 ]
 [2.1289 8.0008]
 [7.9045 8.1401]]
Cluster assignments: [0 0 0 0 0 0 0 0 0 0]...
Cluster sizes: [50 50 50]


### 10.3 Data Preprocessing Pipeline

In [29]:
# Simulate a dataset with missing values and outliers
np.random.seed(42)
data = np.random.randn(100, 3) * 10 + 50

# Add missing values (represented as NaN)
data[5:10, 0] = np.nan
data[15:20, 1] = np.nan

# Add outliers
data[25, :] = [200, 200, 200]

print("Original data shape:", data.shape)
print("Data with missing values:\n", data[:12, :])
print()

# 1. Handle missing values
print("=== Handling Missing Values ===")
print(f"Missing values per column: {np.isnan(data).sum(axis=0)}")

# Fill missing values with column mean
column_means = np.nanmean(data, axis=0)
for col in range(data.shape[1]):
    data[np.isnan(data[:, col]), col] = column_means[col]

print(f"After imputation, missing values: {np.isnan(data).sum()}")
print()

# 2. Remove outliers using Z-score
print("=== Outlier Detection & Removal ===")
z_scores = np.abs((data - np.mean(data, axis=0)) / np.std(data, axis=0))
outlier_mask = (z_scores > 3).any(axis=1)
print(f"Outliers detected: {outlier_mask.sum()}")

data_clean = data[~outlier_mask]
print(f"Shape after removing outliers: {data_clean.shape}")
print()

# 3. Standardization (Z-score normalization)
mean = np.mean(data_clean, axis=0)
std = np.std(data_clean, axis=0)
data_standardized = (data_clean - mean) / std

print("=== After Standardization ===")
print(f"Mean: {np.mean(data_standardized, axis=0)}")
print(f"Std: {np.std(data_standardized, axis=0)}")
print()

# 4. Min-Max Scaling (0 to 1)
data_min = np.min(data_clean, axis=0)
data_max = np.max(data_clean, axis=0)
data_minmax = (data_clean - data_min) / (data_max - data_min)

print("=== After Min-Max Scaling ===")
print(f"Min: {np.min(data_minmax, axis=0)}")
print(f"Max: {np.max(data_minmax, axis=0)}")
print(f"Sample:\n{data_minmax[:5]}")

Original data shape: (100, 3)
Data with missing values:
 [[54.9671 48.6174 56.4769]
 [65.2303 47.6585 47.6586]
 [65.7921 57.6743 45.3053]
 [55.4256 45.3658 45.3427]
 [52.4196 30.8672 32.7508]
 [    nan 39.8717 53.1425]
 [    nan 35.877  64.6565]
 [    nan 50.6753 35.7525]
 [    nan 51.1092 38.4901]
 [    nan 43.9936 47.0831]
 [43.9829 68.5228 49.865 ]
 [39.4229 58.2254 37.7916]]

=== Handling Missing Values ===
Missing values per column: [5 5 0]
After imputation, missing values: 0

=== Outlier Detection & Removal ===
Outliers detected: 1
Shape after removing outliers: (99, 3)

=== After Standardization ===
Mean: [0. 0. 0.]
Std: [1. 1. 1.]

=== After Min-Max Scaling ===
Min: [0. 0. 0.]
Max: [1. 1. 1.]
Sample:
[[0.5978 0.5585 0.5048]
 [0.8484 0.5412 0.3686]
 [0.8621 0.7215 0.3322]
 [0.609  0.5    0.3328]
 [0.5357 0.239  0.1383]]
After imputation, missing values: 0

=== Outlier Detection & Removal ===
Outliers detected: 1
Shape after removing outliers: (99, 3)

=== After Standardization =

### 10.4 Monte Carlo Simulation (Session 17 - Simulation & Risk Analysis)

In [30]:
# Monte Carlo Simulation: Estimating Pi
np.random.seed(42)

n_simulations = 100000
x = np.random.uniform(-1, 1, n_simulations)
y = np.random.uniform(-1, 1, n_simulations)

# Points inside the circle (x^2 + y^2 <= 1)
inside_circle = (x**2 + y**2) <= 1
pi_estimate = 4 * np.sum(inside_circle) / n_simulations

print(f"Number of simulations: {n_simulations}")
print(f"Points inside circle: {np.sum(inside_circle)}")
print(f"Estimated Pi: {pi_estimate:.6f}")
print(f"Actual Pi: {np.pi:.6f}")
print(f"Error: {abs(pi_estimate - np.pi):.6f}")
print()

# Monte Carlo Simulation: Portfolio Risk Analysis
print("=== Portfolio Risk Simulation ===")

# Simulate daily returns for 3 assets
mean_returns = np.array([0.001, 0.0012, 0.0008])  # Expected daily returns
cov_matrix = np.array([
    [0.0004, 0.0001, 0.0002],
    [0.0001, 0.0005, 0.0001],
    [0.0002, 0.0001, 0.0003]
])

n_days = 252  # Trading days in a year
n_simulations = 10000
portfolio_weights = np.array([0.4, 0.35, 0.25])

# Simulate returns
simulated_returns = np.random.multivariate_normal(mean_returns, cov_matrix, (n_simulations, n_days))
portfolio_returns = simulated_returns @ portfolio_weights

# Calculate cumulative returns
cumulative_returns = np.cumprod(1 + portfolio_returns, axis=1)
final_values = cumulative_returns[:, -1]

print(f"Mean final portfolio value: {np.mean(final_values):.4f}")
print(f"Median final portfolio value: {np.median(final_values):.4f}")
print(f"5th percentile (Value at Risk): {np.percentile(final_values, 5):.4f}")
print(f"95th percentile: {np.percentile(final_values, 95):.4f}")
print(f"Probability of loss: {(final_values < 1).sum() / n_simulations * 100:.2f}%")

Number of simulations: 100000
Points inside circle: 78603
Estimated Pi: 3.144120
Actual Pi: 3.141593
Error: 0.002527

=== Portfolio Risk Simulation ===
Mean final portfolio value: 1.2917
Median final portfolio value: 1.2561
5th percentile (Value at Risk): 0.8506
95th percentile: 1.8562
Probability of loss: 16.59%
Mean final portfolio value: 1.2917
Median final portfolio value: 1.2561
5th percentile (Value at Risk): 0.8506
95th percentile: 1.8562
Probability of loss: 16.59%


### 10.5 Gradient Descent from Scratch (Foundation for Neural Networks)

In [31]:
# Simple gradient descent for linear regression
np.random.seed(42)

# Generate data
X = np.random.randn(100, 1)
y = 4 + 3 * X + np.random.randn(100, 1) * 0.5

# Add intercept term
X_with_intercept = np.hstack([np.ones((100, 1)), X])

# Initialize parameters
theta = np.random.randn(2, 1)
learning_rate = 0.01
n_iterations = 1000

# Gradient Descent
for iteration in range(n_iterations):
    # Predictions
    predictions = X_with_intercept @ theta
    
    # Calculate errors
    errors = predictions - y
    
    # Calculate gradients
    gradients = 2/len(X) * X_with_intercept.T @ errors
    
    # Update parameters
    theta = theta - learning_rate * gradients
    
    # Print progress every 100 iterations
    if iteration % 100 == 0:
        mse = np.mean(errors ** 2)
        print(f"Iteration {iteration}: MSE = {mse:.4f}, theta = {theta.ravel()}")

print(f"\nFinal parameters: intercept = {theta[0, 0]:.4f}, slope = {theta[1, 0]:.4f}")
print("True parameters: intercept = 4.0, slope = 3.0")

Iteration 0: MSE = 16.3583, theta = [0.4258 0.5924]
Iteration 100: MSE = 0.7604, theta = [3.4382 2.358 ]
Iteration 200: MSE = 0.2420, theta = [3.9075 2.7996]
Iteration 300: MSE = 0.2218, theta = [3.9863 2.9003]
Iteration 400: MSE = 0.2209, theta = [4.0004 2.9224]
Iteration 500: MSE = 0.2209, theta = [4.0031 2.9271]
Iteration 600: MSE = 0.2209, theta = [4.0036 2.9281]
Iteration 700: MSE = 0.2209, theta = [4.0037 2.9283]
Iteration 800: MSE = 0.2209, theta = [4.0037 2.9284]
Iteration 900: MSE = 0.2209, theta = [4.0037 2.9284]

Final parameters: intercept = 4.0037, slope = 2.9284
True parameters: intercept = 4.0, slope = 3.0


## 11. NumPy Best Practices for AI Engineers

Key tips for writing efficient and maintainable code.

### Key Principles:

1. **Always use vectorization** - Avoid Python loops when possible
2. **Preallocate arrays** - Don't grow arrays dynamically
3. **Use views instead of copies** - Save memory with slicing
4. **Choose appropriate data types** - Use `float32` instead of `float64` when precision isn't critical
5. **Use in-place operations** - `+=`, `*=` etc. to save memory
6. **Leverage broadcasting** - Avoid unnecessary reshaping
7. **Use built-in functions** - NumPy's C-optimized functions are faster than custom implementations
8. **Set random seeds** - For reproducible results
9. **Profile your code** - Use `%timeit` in Jupyter to find bottlenecks
10. **Memory management** - Delete large arrays when done: `del array`

### Common Gotchas:

- Slicing creates views, not copies (modifying a slice changes the original)
- Integer division: Use `/` for float division, `//` for integer division
- Array comparisons return boolean arrays, not single True/False
- `reshape` vs `resize`: reshape returns a view, resize modifies in-place
- Use `.copy()` when you need an independent array

In [32]:
# Example: View vs Copy
arr = np.array([1, 2, 3, 4, 5])

# Slicing creates a view
view = arr[1:4]
view[0] = 999
print("Original after modifying view:", arr)  # Original is modified!

# Use .copy() for independent arrays
arr = np.array([1, 2, 3, 4, 5])
copy = arr[1:4].copy()
copy[0] = 999
print("Original after modifying copy:", arr)  # Original unchanged
print()

# Memory-efficient operations
large_array = np.random.randn(1000, 1000)

# Good: In-place operation
large_array += 10

# Bad: Creates a new array
# large_array = large_array + 10

print("In-place operations are memory-efficient!")

Original after modifying view: [  1 999   3   4   5]
Original after modifying copy: [1 2 3 4 5]

In-place operations are memory-efficient!


## 12. Practice Exercises

Test your understanding with these exercises aligned with the DBDA curriculum.

### Exercise 1: Statistical Analysis
Create a dataset of 1000 random numbers from a normal distribution (mean=100, std=15).
Calculate and print:
- Mean, median, mode
- Variance and standard deviation
- Quartiles and IQR
- Identify and remove outliers
- Create a normalized version of the cleaned data

In [33]:
# Your solution here


### Exercise 2: Correlation Analysis
Create two arrays representing variables with known correlation:
- Generate array X with 200 random values
- Generate array Y = 2*X + noise (to create correlation)
- Calculate covariance and correlation coefficient
- Add a third variable Z that is independent of X and Y
- Create a correlation matrix for all three variables

In [34]:
# Your solution here


### Exercise 3: Probability Distributions
- Generate 10,000 samples from a binomial distribution (n=20, p=0.3)
- Generate 10,000 samples from a normal distribution (mean=50, std=10)
- Calculate the mean and standard deviation of both samples
- Count how many values in the normal distribution fall within 1, 2, and 3 standard deviations from the mean
- Verify the 68-95-99.7 rule

In [35]:
# Your solution here


### Exercise 4: Matrix Operations for Machine Learning
Create two matrices:
- X: A 100x3 feature matrix (random values)
- y: A 100x1 target vector (y = 2*X[:,0] + 3*X[:,1] - 1*X[:,2] + noise)

Tasks:
1. Add a bias column to X (column of ones)
2. Solve for weights using the normal equation: w = (X^T X)^(-1) X^T y
3. Calculate predictions
4. Calculate Mean Squared Error
5. Calculate R-squared

In [36]:
# Your solution here


### Exercise 5: Monte Carlo Simulation
Simulate a simple investment scenario:
- Initial investment: $10,000
- Expected annual return: 8% (mean)
- Annual volatility: 15% (standard deviation)
- Investment period: 10 years
- Run 10,000 simulations

Calculate:
- Mean final portfolio value
- Median final portfolio value
- 5th and 95th percentiles
- Probability of doubling your money
- Probability of losing money

In [37]:
# Your solution here


## 13. Summary & Next Steps

### What You've Learned:
✅ NumPy fundamentals: arrays, indexing, slicing  
✅ Array manipulation and reshaping  
✅ Mathematical and statistical operations  
✅ Probability distributions and random number generation  
✅ Linear algebra operations  
✅ Broadcasting and vectorization  
✅ Real-world ML applications  

### DBDA Curriculum Alignment:
- **Sessions 5-6**: Correlation, Covariance, Outliers ✓
- **Sessions 7-8**: Probability Distributions ✓
- **Sessions 9-10**: Descriptive Statistics ✓
- **Sessions 11-12**: Sampling & Central Limit Theorem ✓
- **Session 17**: Monte Carlo Simulation ✓

### Next Steps:
1. **Practice**: Complete all exercises in Section 12
2. **Integration**: Learn pandas for structured data analysis
3. **Visualization**: Learn matplotlib/seaborn for data visualization
4. **Advanced**: Dive into scipy for hypothesis testing and statistical inference
5. **ML Libraries**: Explore scikit-learn (built on NumPy)
6. **Deep Learning**: TensorFlow/PyTorch (NumPy-like syntax)

### Resources:
- Official NumPy Documentation: https://numpy.org/doc/
- NumPy User Guide: https://numpy.org/doc/stable/user/
- From Python to NumPy: https://www.labri.fr/perso/nrougier/from-python-to-numpy/

### Key Takeaway:
NumPy is the foundation of the entire Python data science ecosystem. Mastering it is essential for becoming a proficient AI/ML engineer!