In [79]:
import numpy as np
import pandas as pd
import scipy
from scipy import stats
from scipy.stats import norm, t, binom, poisson, expon, chi2, f
import matplotlib.pyplot as plt
import seaborn as sns
import statsmodels
import statsmodels.api as sm
from statsmodels import stats as sm_stats
from statsmodels.stats import weightstats as sswa
from statsmodels.formula.api import ols
from statsmodels.stats.multicomp import pairwise_tukeyhsd
from statsmodels.stats import proportion as ssp
from statsmodels.stats.proportion import proportions_ztest
import os
import warnings
warnings.filterwarnings("ignore")
from scipy.stats import chi2_contingency

In [80]:
"""
TWO SAMPLE PROPORTION TEST

- this test is used to compare the difference of two sample proportions
against a claim value and establish whether the difference between them is 
statistically significant or not

"""

# I claim that CDAC Mumbai has atleast 12% more engineers as compared to pune

# Ho: prop(M) - prop(P) >= 0.12
# Ha: prop(M) - prop(P) < 0.12

CL = 0.95
LoS = 0.05

# In a nbatch of 70 students in Mumbai , 45 are engineers
# In a nbatch of 100 students in Mumbai , 60 are engineers

engg = np.array([45,60])
counts = np.array([70,100])

ssp.proportions_ztest(engg,counts,value=0.12,alternative='smaller')
# => (np.float64(-1.018633307307723), np.float64(0.15418854277526844))
# since p-value is greater than LoS hence we do not reject the Ho

(45/70) - (60/100)
# => 0.04285714285714293

0.04285714285714293

In [81]:
engg = np.array([45,60])
counts = np.array([70,100])

In [82]:
# In a batch of 70 students in Mumbai, 45 are engineers
# In a batch of 100 students in Pune, 60 are engineers

In [83]:
ssp.proportions_ztest(engg, counts, value=0.12, alternative = 'smaller')

(np.float64(-1.018633307307723), np.float64(0.15418854277526844))

In [84]:
45/70 - 60/100

0.04285714285714293

In [85]:
# chi square test

# single categorical variables with 
# the counts obtained for different categories or levels received from the sample need to be compared against the claimed pattern, weather the diffeerence is statistically significant or not

In [86]:
pattern = np.array([0.35, 0.3,0.15,0.12,0.08])
obs_counts = np.array([120, 105, 80,50,30])

In [87]:
sum(obs_counts)

np.int64(385)

In [88]:
exp_counts = pattern * sum(obs_counts)

In [89]:
exp_counts

array([134.75, 115.5 ,  57.75,  46.2 ,  30.8 ])

In [90]:
scipy.stats.chisquare(obs_counts, f_exp= exp_counts)

Power_divergenceResult(statistic=np.float64(11.474953617810764), pvalue=np.float64(0.021714146578774157))

In [91]:
# above we can conclude that the counts do not meet the given pattern

In [92]:
ts_array = (obs_counts - exp_counts) ** 2/ (exp_counts)

In [93]:
ts_array  # so here the hyundai is the most statistically significant with 8.572

array([1.61456401, 0.95454545, 8.57251082, 0.31255411, 0.02077922])

In [94]:
sum(ts_array)

np.float64(11.474953617810764)

In [95]:
# degree of association will be used where we have two categorical variables
# the number of levels for each categorical variables may not be the same
# this test is used to check the choice made from the level of one variable depends on the level of the second variable

In [96]:
pattern = np.array([0.25, 0.25, 0.25, 0.25])
obs_count = np.array([5,5,5,5])

In [97]:
exp_counts = sum(obs_count) * pattern

In [98]:
scipy.stats.chisquare(obs_count, exp_counts)

Power_divergenceResult(statistic=np.float64(0.0), pvalue=np.float64(1.0))

In [99]:
# Ho - the two variables are not associated with each other
# or type of food doesn't depend on gender

# categories = [male, female]
    # veg       -  110,120
    # nonveg    -  150, 80
    # fastfood  -  40,90

In [100]:
data = np.array([[110,150,40], [120,80,90]])

In [101]:
chi2_contingency(data)

Chi2ContingencyResult(statistic=np.float64(40.81213239534079), pvalue=np.float64(1.3732767045277907e-09), dof=2, expected_freq=array([[116.94915254, 116.94915254,  66.10169492],
       [113.05084746, 113.05084746,  63.89830508]]))

In [102]:
# ddof = (count(row) -1 ) * (count (column) -1)

In [103]:
exp_values = chi2_contingency(data)[3]

In [104]:
exp_values          # expected values

array([[116.94915254, 116.94915254,  66.10169492],
       [113.05084746, 113.05084746,  63.89830508]])

In [105]:
data                 # our data

array([[110, 150,  40],
       [120,  80,  90]])

In [106]:
ts = (exp_values-data)**2/exp_values

In [107]:
ts

array([[ 0.41292066,  9.34045689, 10.30682312],
       [ 0.4271593 ,  9.66254161, 10.66223081]])

In [108]:
sum(sum(ts))

np.float64(40.81213239534079)

In [109]:
# one sample poisson rate
# this tool is used to compare the rate at which on even t occurs in a sample against a claim value esastablish weather thediff is statisticaly significant or not

In [110]:
from statsmodels.stats import rates
from statsmodels.stats.rates import test_poisson

In [111]:
# no of accidents are limited to 12 per day
# H0 n <=12 , Ha n > 12
# In a sample of 10 days, there were 135 accidents. Does this data justify the claim

In [112]:
test_poisson(135, 10, 12, method = 'score', alternative = 'larger')

<class 'statsmodels.stats.base.HolderTuple'>
statistic = np.float64(1.3693063937629153)
pvalue = np.float64(0.08545176011539873)
distribution = 'normal'
method = 'score'
alternative = 'larger'
rate = 13.5
nobs = 10
tuple = (np.float64(1.3693063937629153), np.float64(0.08545176011539873))

In [113]:
# two sample poisson rate
# difference of the rate of the event occuring in two different samples against a claim value and establish

In [114]:
from statsmodels.stats.rates import test_poisson_2indep

In [115]:
# Ho rate(Mumabi) - rate(Blore) >=4
# Ho rate(Mumabi) - rate(Blore) <4

# 135 accidents reported in 10 days in Mumbai
# 120 accidents reported in 15 days in Blore
# 130 accidents reported in 15 days in Blore

In [116]:
test_poisson_2indep(135,10,130,15, value = 4, compare ='diff', method = 'score', alternative='smaller')

<class 'statsmodels.stats.base.HolderTuple'>
statistic = np.float64(0.6064446508174207)
pvalue = np.float64(0.7278902369856597)
distribution = 'normal'
compare = 'diff'
method = 'score'
alternative = 'smaller'
rates = (np.float64(13.5), np.float64(8.666666666666666))
ratio = np.float64(1.5576923076923077)
diff = np.float64(4.833333333333334)
value = 4
rates_cmle = (np.float64(12.929387178015027), np.float64(8.929387178015027))
ratio_null = None
tuple = (np.float64(0.6064446508174207), np.float64(0.7278902369856597))

In [117]:
from scipy.stats import chi2

In [120]:
os.chdir(r'/Users/proxim/Desktop/CDAC-DBDA-coursework/08.advanced-analytics-stats')

In [121]:
df=pd.read_excel('data/CDAC_DataBook.xlsx', sheet_name='faithful')

In [123]:
erupt = df.eruptions

In [124]:
np.var(erupt, ddof =1)

np.float64(1.302728332849468)

In [127]:
scipy.stats.chi2.ppf(0.025, len(erupt)-1)

np.float64(227.29308712885378)

In [126]:
scipy.stats.chi2.ppf(0.925, len(erupt)-1)

np.float64(305.19435553548107)

In [ ]:
1.302728332849468 * 

In [ ]:
# 1 sample z test = 
