In [ ]:
import os
os.chdir(r'/Users/proxim/Desktop/CDAC-DBDA-coursework/08.advanced-analytics-stats')

In [256]:
import numpy as np

In [257]:
import pandas as pd

In [258]:
a1 = np.array([4,5,6,7,8])

In [259]:
type(a1)

numpy.ndarray

In [260]:
a2 = np.array([3,4,3,2])

In [261]:
a2

array([3, 4, 3, 2])

In [262]:
a = np.concatenate((a1,a2))

In [263]:
a

array([4, 5, 6, 7, 8, 3, 4, 3, 2])

In [264]:
a1 = np.insert(a1,3,10)

In [265]:
a1

array([ 4,  5,  6, 10,  7,  8])

In [266]:

a1 = np.insert(a1,6,np.array([7,6,9]))

In [267]:
a1

array([ 4,  5,  6, 10,  7,  8,  7,  6,  9])

In [268]:
a1 = np.delete(a1,6)

In [269]:
a1

array([ 4,  5,  6, 10,  7,  8,  6,  9])

In [270]:
my_list = list(range(1,6))

In [271]:
my_list

[1, 2, 3, 4, 5]

In [272]:
a1 = np.arange(1,11)

In [273]:
a1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [274]:
a1 = np.arange(1,26,3)

In [275]:
a1

array([ 1,  4,  7, 10, 13, 16, 19, 22, 25])

In [276]:
a1 = np.arange(40,7,-3)

In [277]:
a1

array([40, 37, 34, 31, 28, 25, 22, 19, 16, 13, 10])

In [278]:
x2 = list(a1)

In [279]:
x2

[np.int64(40),
 np.int64(37),
 np.int64(34),
 np.int64(31),
 np.int64(28),
 np.int64(25),
 np.int64(22),
 np.int64(19),
 np.int64(16),
 np.int64(13),
 np.int64(10)]

In [280]:
# list is just single dimensional
# while array could be multi-dimensional

In [281]:
i = 34
a = i + x2[1]
print(a)

71


In [282]:
a1 = np.array([3,6,5,8,6,4,3,2,8,7,8,9])
a1

array([3, 6, 5, 8, 6, 4, 3, 2, 8, 7, 8, 9])

In [283]:
a2 = a1.reshape(3,4)    # two dimensional

In [284]:
a2

array([[3, 6, 5, 8],
       [6, 4, 3, 2],
       [8, 7, 8, 9]])

In [285]:
# array([[         two square brackets are means two dimensional array

#]])

In [286]:
a3 = a1.reshape(3,2,2) # three dimensional arra    (read as 2*2 stacked on top with height of 3)

In [287]:
a3

array([[[3, 6],
        [5, 8]],

       [[6, 4],
        [3, 2]],

       [[8, 7],
        [8, 9]]])

In [288]:
k1 = [3,5,7,9]
k2 = [1,3,2,5]
k3 = [7,5,9,2]

k4 = np.array([k1,k2,k3])

In [289]:
k4

array([[3, 5, 7, 9],
       [1, 3, 2, 5],
       [7, 5, 9, 2]])

In [290]:
k4[1]

array([1, 3, 2, 5])

In [291]:
k4[[1,2]]

array([[1, 3, 2, 5],
       [7, 5, 9, 2]])

In [292]:
k4 [:,[1,3]]

array([[5, 9],
       [3, 5],
       [5, 2]])

In [293]:
b = k4[:,1]

In [294]:
b

array([5, 3, 5])

In [295]:
b1 = b.reshape(-1,1)
b1

array([[5],
       [3],
       [5]])

In [296]:
k4.flatten(order='c')

array([3, 5, 7, 9, 1, 3, 2, 5, 7, 5, 9, 2])

In [297]:
k4.flatten(order='f')

array([3, 1, 7, 5, 3, 5, 7, 2, 9, 9, 5, 2])

In [298]:
k4.transpose()

array([[3, 1, 7],
       [5, 3, 5],
       [7, 2, 9],
       [9, 5, 2]])

In [299]:
newrow = np.array([1,5,7,6])

In [300]:
a1 = np.vstack([k4, newrow])

In [301]:
a1

array([[3, 5, 7, 9],
       [1, 3, 2, 5],
       [7, 5, 9, 2],
       [1, 5, 7, 6]])

In [302]:
newcol = np.array([14,12,19])

In [303]:
newcol

array([14, 12, 19])

In [304]:
newcol = newcol.reshape(-1,1)

In [305]:
newcol

array([[14],
       [12],
       [19]])

In [306]:
a1 = np.hstack([k4, newcol])

In [307]:
a1

array([[ 3,  5,  7,  9, 14],
       [ 1,  3,  2,  5, 12],
       [ 7,  5,  9,  2, 19]])

In [308]:
a1 = a1.transpose()

In [309]:
a1

array([[ 3,  1,  7],
       [ 5,  3,  5],
       [ 7,  2,  9],
       [ 9,  5,  2],
       [14, 12, 19]])

In [310]:
a1 = np.insert(a1,2,[3,5,7], axis = 0)
a1

array([[ 3,  1,  7],
       [ 5,  3,  5],
       [ 3,  5,  7],
       [ 7,  2,  9],
       [ 9,  5,  2],
       [14, 12, 19]])

In [311]:
# Insert a column with one value per row (a1 has 6 rows). The original list had 7 items causing a shape mismatch.
a1 = np.insert(a1, 1, [3, 5, 7, 1, 3, 4], axis=1)
a1

array([[ 3,  3,  1,  7],
       [ 5,  5,  3,  5],
       [ 3,  7,  5,  7],
       [ 7,  1,  2,  9],
       [ 9,  3,  5,  2],
       [14,  4, 12, 19]])

In [312]:
np.delete(a1, (0,2), axis = 0)

array([[ 5,  5,  3,  5],
       [ 7,  1,  2,  9],
       [ 9,  3,  5,  2],
       [14,  4, 12, 19]])

In [313]:
np.delete(a1,(0,2), axis = 1)

array([[ 3,  7],
       [ 5,  5],
       [ 7,  7],
       [ 1,  9],
       [ 3,  2],
       [ 4, 19]])

In [314]:
# broadcasting in array

In [315]:
a1 = a1+2      # add 2 in every element in array

In [316]:
a1

array([[ 5,  5,  3,  9],
       [ 7,  7,  5,  7],
       [ 5,  9,  7,  9],
       [ 9,  3,  4, 11],
       [11,  5,  7,  4],
       [16,  6, 14, 21]])

In [317]:
a2 =  np.array([1,2,3,4,5,6,7])

In [318]:
# column wise addition — ensure a2 length matches a1 rows
a1 + a2[:a1.shape[0]].reshape(-1,1)

array([[ 6,  6,  4, 10],
       [ 9,  9,  7,  9],
       [ 8, 12, 10, 12],
       [13,  7,  8, 15],
       [16, 10, 12,  9],
       [22, 12, 20, 27]])

In [319]:
a2 = a2.reshape(-1,1)

In [320]:
a2

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7]])

In [321]:
b1 = np.array([1,2,3,4,5,6])

In [322]:
b1 * 2

array([ 2,  4,  6,  8, 10, 12])

In [323]:
d1 = np.array([1,2,4,5,61])
d0 = np.repeat(d1,[1,2,3,4,5])


In [324]:
d0

array([ 1,  2,  2,  4,  4,  4,  5,  5,  5,  5, 61, 61, 61, 61, 61])

In [325]:
np.sort(d0)

array([ 1,  2,  2,  4,  4,  4,  5,  5,  5,  5, 61, 61, 61, 61, 61])

In [326]:
np.sort(b1)[::-1]

array([6, 5, 4, 3, 2, 1])

In [327]:
np.argsort(b1)

array([0, 1, 2, 3, 4, 5])

In [328]:
np.sort(a1, axis = 0)

array([[ 5,  3,  3,  4],
       [ 5,  5,  4,  7],
       [ 7,  5,  5,  9],
       [ 9,  6,  7,  9],
       [11,  7,  7, 11],
       [16,  9, 14, 21]])

In [329]:
b1 = np.array([12,1,41,1,5,11,14,])

In [330]:
np.where(b1>=4)

(array([0, 2, 4, 5, 6]),)

In [331]:
t1 = np.where(b1>4)

In [332]:
len(t1)

1

In [333]:
len(t1[0])

5

In [334]:
b1[[1,3,5]]

array([ 1,  1, 11])

In [335]:
len(np.where(b1>=4)[0])

5

In [336]:
(b1>=4).sum()

np.int64(5)

In [337]:
t1

(array([0, 2, 4, 5, 6]),)

In [338]:
len(t1[0])

5

In [339]:
(a1>=4).sum()

np.int64(22)

In [340]:
np.unique(b1)

array([ 1,  5, 11, 12, 14, 41])

In [341]:
np.unique(b1, return_index=True)

(array([ 1,  5, 11, 12, 14, 41]), array([1, 4, 5, 0, 6, 2]))

In [342]:
np.unique(b1, return_counts=True)

(array([ 1,  5, 11, 12, 14, 41]), array([2, 1, 1, 1, 1, 1]))

In [343]:
np.unique(b1, return_inverse=True)          # for every unique element as reference from the unique elements we are just returning the index from the orignal b1

(array([ 1,  5, 11, 12, 14, 41]), array([3, 0, 5, 0, 1, 2, 4]))

In [344]:
import numpy as np
x1 = np.array([1,2,3,2,1])
x2 = np.array([1,2,6,5,6])


In [345]:
np.intersect1d(x1,x2)

array([1, 2])

In [346]:
np.union1d(x1,x2)

array([1, 2, 3, 5, 6])

In [347]:
np.setdiff1d(x2,x1)

array([5, 6])

In [348]:
x3 = np.array([4,10,2,5])

In [349]:
x3

array([ 4, 10,  2,  5])

In [350]:
x1

array([1, 2, 3, 2, 1])

In [351]:
np.in1d(x1,x3)

/var/folders/57/62f2rv1j4w94h8tfp_c43b1c0000gn/T/ipykernel_61606/2081356283.py:1: DeprecationWarning: `in1d` is deprecated. Use `np.isin` instead.
  np.in1d(x1,x3)


array([False,  True, False,  True, False])

In [352]:
np.where(np.in1d(x1,x3))

/var/folders/57/62f2rv1j4w94h8tfp_c43b1c0000gn/T/ipykernel_61606/573868696.py:1: DeprecationWarning: `in1d` is deprecated. Use `np.isin` instead.
  np.where(np.in1d(x1,x3))


(array([1, 3]),)

In [353]:
a1 = np.array([[1,4,7],[2,3,6]])

In [354]:
a1

array([[1, 4, 7],
       [2, 3, 6]])

In [355]:
a2  = np.array([[1,5],[0,2],[5,3]])

In [356]:
a2

array([[1, 5],
       [0, 2],
       [5, 3]])

In [357]:
a1.dot(a2)

array([[36, 34],
       [32, 34]])

In [358]:
np.matmul(a1,a2)

array([[36, 34],
       [32, 34]])

In [359]:
a3 = ([[1,2,3],[4,2,1],[3,2,6]])

In [360]:
a3

[[1, 2, 3], [4, 2, 1], [3, 2, 6]]

In [361]:
np.linalg.inv(a3)

array([[-0.38461538,  0.23076923,  0.15384615],
       [ 0.80769231,  0.11538462, -0.42307692],
       [-0.07692308, -0.15384615,  0.23076923]])

In [362]:
a3 = np.array([[1,2,3],[4,2,1],[3,2,6]])

In [363]:
a3

array([[1, 2, 3],
       [4, 2, 1],
       [3, 2, 6]])

In [364]:
from numpy import random

In [365]:
rd.rand(10)

NameError: name 'rd' is not defined

In [ ]:
np.round(rd.rand(10),3)

In [ ]:
np.round(rd.rand(40),3)

In [ ]:
numbers_between_10_and_40 = np.arange(10, 41)
print(numbers_between_10_and_40)

In [ ]:
np.random.randint(20,50)

In [ ]:
np.random.randint(20,50,10)

![img](https://i.sstatic.net/Tbe9W.png)

In [ ]:
a1 = np.hstack([a1,g1])