In [648]:
import pandas as pd
import os
import numpy as np

In [649]:
os.chdir(r'/Users/proxim/Desktop/CDAC-DBDA-coursework/08.advanced-analytics-stats')

In [650]:
s1 = pd.Series([4,7,6,8,9])

In [651]:
s1

0    4
1    7
2    6
3    8
4    9
dtype: int64

In [652]:
s1[2]

np.int64(6)

In [653]:
s1[1:4]

1    7
2    6
3    8
dtype: int64

In [654]:
s1 = pd.Series([4,7,6,8,9], index = ['A','B','C','D','E'])

In [655]:
s1

A    4
B    7
C    6
D    8
E    9
dtype: int64

In [656]:
s1.iloc[2] # extracting from inbuild index =  index reference, [note - we can also pass the loc reference in iloc]

np.int64(6)

In [657]:
s1.loc['C'] # extracting from custom index = label reference which is custom


# also the custom labes could be duplicate such as index = ['A','B','A','B']

np.int64(6)

In [658]:
s1.iloc[[1,3]]

B    7
D    8
dtype: int64

In [659]:
s2 = s1.iloc[[1,3]]

In [660]:
s2

B    7
D    8
dtype: int64

In [661]:
# we can also make the custom index and custom elements with the help of dictionary

In [662]:
d1 = {'A':2, 'B':7,'C':8}

In [663]:
d1

{'A': 2, 'B': 7, 'C': 8}

In [664]:
s2 = pd.Series(d1)

In [665]:
s2

A    2
B    7
C    8
dtype: int64

In [666]:
s3 = pd.Series([5,3], index = ['D','E'])

In [667]:
s3

D    5
E    3
dtype: int64

In [668]:
s2 = pd.concat([s2,s3])

In [669]:
s2

A    2
B    7
C    8
D    5
E    3
dtype: int64

In [670]:
s3

D    5
E    3
dtype: int64

In [671]:
s2.loc['B'] = 17

In [672]:
s2

A     2
B    17
C     8
D     5
E     3
dtype: int64

In [673]:
s2.drop(s2.index[2])

A     2
B    17
D     5
E     3
dtype: int64

In [674]:
s2.drop('C')

A     2
B    17
D     5
E     3
dtype: int64

In [675]:
df = pd.DataFrame([['A',25,76], ['B',45, 90], ['C',26,58]], columns = ['Name', 'RollNo', 'Marks'])

In [676]:
df

,Name,RollNo,Marks
0,A,25,76
1,B,45,90
2,C,26,58


In [677]:
d1 = {'PlayerName' :['Sachin', 'Dhoni', 'Gill', 'Surya'], 'Team':['MI','CSK', 'GT','MI']}

In [678]:
d1

{'PlayerName': ['Sachin', 'Dhoni', 'Gill', 'Surya'],
 'Team': ['MI', 'CSK', 'GT', 'MI']}

In [679]:
newdf = pd.DataFrame([['H',25, 68], ['R',26, 45]], columns=['XYZ','LMQ', 'PQR'])

In [680]:
newdf

,XYZ,LMQ,PQR
0,H,25,68
1,R,26,45


In [681]:
df = pd.concat([df, newdf])

In [682]:
newdf

,XYZ,LMQ,PQR
0,H,25,68
1,R,26,45


In [683]:
df.iloc[[1,3]]

,Name,RollNo,Marks,XYZ,LMQ,PQR
1,B,45.0,90.0,NaN,NaN,NaN
0,NaN,NaN,NaN,H,25.0,68.0


In [684]:
df2 = pd.concat([df, newdf]).reset_index(drop=True)

In [685]:
df2

,Name,RollNo,Marks,XYZ,LMQ,PQR
0,A,25.0,76.0,NaN,NaN,NaN
1,B,45.0,90.0,NaN,NaN,NaN
2,C,26.0,58.0,NaN,NaN,NaN
3,NaN,NaN,NaN,H,25.0,68.0
4,NaN,NaN,NaN,R,26.0,45.0
5,NaN,NaN,NaN,H,25.0,68.0
6,NaN,NaN,NaN,R,26.0,45.0


In [686]:
df2 = pd.concat([df, newdf]).reset_index()  # add back index

In [687]:
df2

,index,Name,RollNo,Marks,XYZ,LMQ,PQR
0,0,A,25.0,76.0,NaN,NaN,NaN
1,1,B,45.0,90.0,NaN,NaN,NaN
2,2,C,26.0,58.0,NaN,NaN,NaN
3,0,NaN,NaN,NaN,H,25.0,68.0
4,1,NaN,NaN,NaN,R,26.0,45.0
5,0,NaN,NaN,NaN,H,25.0,68.0
6,1,NaN,NaN,NaN,R,26.0,45.0


In [688]:
x1 = [45,68,76,89,2,34,1]

In [689]:
df2['marks2'] = x1

In [690]:
df2

,index,Name,RollNo,Marks,XYZ,LMQ,PQR,marks2
0,0,A,25.0,76.0,NaN,NaN,NaN,45
1,1,B,45.0,90.0,NaN,NaN,NaN,68
2,2,C,26.0,58.0,NaN,NaN,NaN,76
3,0,NaN,NaN,NaN,H,25.0,68.0,89
4,1,NaN,NaN,NaN,R,26.0,45.0,2
5,0,NaN,NaN,NaN,H,25.0,68.0,34
6,1,NaN,NaN,NaN,R,26.0,45.0,1


In [691]:
df2.drop([0,2])

,index,Name,RollNo,Marks,XYZ,LMQ,PQR,marks2
1,1,B,45.0,90.0,NaN,NaN,NaN,68
3,0,NaN,NaN,NaN,H,25.0,68.0,89
4,1,NaN,NaN,NaN,R,26.0,45.0,2
5,0,NaN,NaN,NaN,H,25.0,68.0,34
6,1,NaN,NaN,NaN,R,26.0,45.0,1


In [692]:
df2

,index,Name,RollNo,Marks,XYZ,LMQ,PQR,marks2
0,0,A,25.0,76.0,NaN,NaN,NaN,45
1,1,B,45.0,90.0,NaN,NaN,NaN,68
2,2,C,26.0,58.0,NaN,NaN,NaN,76
3,0,NaN,NaN,NaN,H,25.0,68.0,89
4,1,NaN,NaN,NaN,R,26.0,45.0,2
5,0,NaN,NaN,NaN,H,25.0,68.0,34
6,1,NaN,NaN,NaN,R,26.0,45.0,1


In [693]:
df2 = df2.drop('index', axis=1)

In [694]:
df2

,Name,RollNo,Marks,XYZ,LMQ,PQR,marks2
0,A,25.0,76.0,NaN,NaN,NaN,45
1,B,45.0,90.0,NaN,NaN,NaN,68
2,C,26.0,58.0,NaN,NaN,NaN,76
3,NaN,NaN,NaN,H,25.0,68.0,89
4,NaN,NaN,NaN,R,26.0,45.0,2
5,NaN,NaN,NaN,H,25.0,68.0,34
6,NaN,NaN,NaN,R,26.0,45.0,1


In [695]:
df2.drop(df2.columns[1], axis =1 )

,Name,Marks,XYZ,LMQ,PQR,marks2
0,A,76.0,NaN,NaN,NaN,45
1,B,90.0,NaN,NaN,NaN,68
2,C,58.0,NaN,NaN,NaN,76
3,NaN,NaN,H,25.0,68.0,89
4,NaN,NaN,R,26.0,45.0,2
5,NaN,NaN,H,25.0,68.0,34
6,NaN,NaN,R,26.0,45.0,1


In [696]:
df2.iat[1,2] = 60

In [697]:
df2

,Name,RollNo,Marks,XYZ,LMQ,PQR,marks2
0,A,25.0,76.0,NaN,NaN,NaN,45
1,B,45.0,60.0,NaN,NaN,NaN,68
2,C,26.0,58.0,NaN,NaN,NaN,76
3,NaN,NaN,NaN,H,25.0,68.0,89
4,NaN,NaN,NaN,R,26.0,45.0,2
5,NaN,NaN,NaN,H,25.0,68.0,34
6,NaN,NaN,NaN,R,26.0,45.0,1


In [698]:
df2.at[2,'Marks'] = 68

In [699]:
df2

,Name,RollNo,Marks,XYZ,LMQ,PQR,marks2
0,A,25.0,76.0,NaN,NaN,NaN,45
1,B,45.0,60.0,NaN,NaN,NaN,68
2,C,26.0,68.0,NaN,NaN,NaN,76
3,NaN,NaN,NaN,H,25.0,68.0,89
4,NaN,NaN,NaN,R,26.0,45.0,2
5,NaN,NaN,NaN,H,25.0,68.0,34
6,NaN,NaN,NaN,R,26.0,45.0,1


In [700]:
erp = pd.read_excel('data/CDAC_DataBook.xlsx', sheet_name='ERPData', engine='openpyxl')

In [701]:
df.head()

,Name,RollNo,Marks,XYZ,LMQ,PQR
0,A,25.0,76.0,NaN,NaN,NaN
1,B,45.0,90.0,NaN,NaN,NaN
2,C,26.0,58.0,NaN,NaN,NaN
0,NaN,NaN,NaN,H,25.0,68.0
1,NaN,NaN,NaN,R,26.0,45.0


In [702]:
df.shape

(5, 6)

In [703]:
df.tail()

,Name,RollNo,Marks,XYZ,LMQ,PQR
0,A,25.0,76.0,NaN,NaN,NaN
1,B,45.0,90.0,NaN,NaN,NaN
2,C,26.0,58.0,NaN,NaN,NaN
0,NaN,NaN,NaN,H,25.0,68.0
1,NaN,NaN,NaN,R,26.0,45.0


In [704]:
df.columns

Index(['Name', 'RollNo', 'Marks', 'XYZ', 'LMQ', 'PQR'], dtype='object')

In [705]:
list(df.columns)

['Name', 'RollNo', 'Marks', 'XYZ', 'LMQ', 'PQR']

In [706]:
df.head()

,Name,RollNo,Marks,XYZ,LMQ,PQR
0,A,25.0,76.0,NaN,NaN,NaN
1,B,45.0,90.0,NaN,NaN,NaN
2,C,26.0,58.0,NaN,NaN,NaN
0,NaN,NaN,NaN,H,25.0,68.0
1,NaN,NaN,NaN,R,26.0,45.0


In [707]:
df.columns.values[1] = 'Location'

In [708]:
erp.head()

,MaterialID,Location,Quantity
0,TMI-43T,MWH-4,34
1,AXCP-78,MWH-1,67
2,LXCV-21,MWH-2,27
3,AXCP-78,MWH-5,65
4,AXCP-78,MWH-4,36


In [709]:
ind = np.where(erp.Location == 'MWH-2')

In [710]:
ind

(array([ 2,  7,  8, 15, 35, 36, 42, 45, 46]),)

In [711]:
df1 = erp.iloc[ind]

In [712]:
df1

,MaterialID,Location,Quantity
2,LXCV-21,MWH-2,27
7,TMI-43T,MWH-2,29
8,GCVB-79,MWH-2,10
15,GCVB-79,MWH-2,87
35,GCVB-79,MWH-2,31
36,GCVB-79,MWH-2,28
42,SDRT-67,MWH-2,31
45,DDBN-89,MWH-2,69
46,AXCP-78,MWH-2,85


In [713]:
ind = np.where(((erp.Location == 'MWH-2') | (erp.Location == 'MWH-4')) & (erp.Quantity >75))

In [714]:
ind

(array([ 5, 12, 15, 46]),)

In [715]:
ind = np.where((erp.Location.isin(['MWH-2', 'MWH-4'])) & (erp.Quantity > 75))

In [716]:
df2 = erp.iloc[ind].reset_index(drop= True)

In [717]:
df2

,MaterialID,Location,Quantity
0,TMI-43T,MWH-4,78
1,TMI-43T,MWH-4,76
2,GCVB-79,MWH-2,87
3,AXCP-78,MWH-2,85


In [718]:
min(erp.Quantity)

10

In [719]:
ind = np.where(erp.Quantity<=40)

In [720]:
ind[0]

array([ 0,  2,  4,  6,  7,  8, 10, 13, 16, 18, 20, 28, 30, 34, 35, 36, 40,
       42, 43, 47, 49])

In [721]:
df1 = erp.drop(ind[0])

In [722]:
min(df1.Quantity)

42

In [723]:
max(df1.Quantity)

152

In [724]:
df = pd.read_excel('data/CDAC_DataBook.xlsx', sheet_name='Pune', engine='openpyxl')

In [725]:
df.head()

,Name,Subject,Grade
0,Rakesh,Python,A
1,Manoj,MLPython,C
2,Vaibhav,Statistics,B
3,Hitesh,CommSkills,A
4,Suyash,ProjectMgmt,B


In [726]:
loc = df.where((df.Subject == 'Python') | (df.Subject == 'MLPython')) 

In [727]:
# `ind` is a tuple returned by np.where, use the first element (array of row indices)
rows = ind[0]
erp.iloc[rows]


,MaterialID,Location,Quantity
0,TMI-43T,MWH-4,34
2,LXCV-21,MWH-2,27
4,AXCP-78,MWH-4,36
6,TMI-43T,MWH-4,31
7,TMI-43T,MWH-2,29
8,GCVB-79,MWH-2,10
10,SDRT-67,MWH-1,34
13,TMI-43T,MWH-4,32
16,SDRT-67,MWH-5,12
18,TMI-43T,MWH-4,34


In [728]:

df1 = loc.dropna(how='all').reset_index(drop=True)

In [729]:
df1

,Name,Subject,Grade
0,Rakesh,Python,A
1,Manoj,MLPython,C


In [730]:
erp.head()

,MaterialID,Location,Quantity
0,TMI-43T,MWH-4,34
1,AXCP-78,MWH-1,67
2,LXCV-21,MWH-2,27
3,AXCP-78,MWH-5,65
4,AXCP-78,MWH-4,36


In [731]:
min_q = erp.Quantity.min()
ind = np.where(erp.Quantity == min_q)

In [732]:
ind

(array([8]),)

In [733]:
# `ind` is a tuple returned by np.where, e.g. (array([8]),)
# use the first element (array of row indices) with iloc.
rows = ind[0]

# If you want all matching rows' first column:
df1 = erp.iloc[rows, 0]

# If you want only the first matching value (scalar), uncomment:
# df1 = erp.iloc[rows[0], 0]

In [734]:
df1

8    GCVB-79
Name: MaterialID, dtype: object

In [735]:
erp

,MaterialID,Location,Quantity
0,TMI-43T,MWH-4,34
1,AXCP-78,MWH-1,67
2,LXCV-21,MWH-2,27
3,AXCP-78,MWH-5,65
4,AXCP-78,MWH-4,36
5,TMI-43T,MWH-4,78
6,TMI-43T,MWH-4,31
7,TMI-43T,MWH-2,29
8,GCVB-79,MWH-2,10
9,TMI-43T,MWH-1,120


In [736]:
ind = np.where(erp.Quantity==min(erp.Quantity))

In [737]:
import pandas as pd

In [738]:
df = pd.read_excel('data/CDAC_DataBook.xlsx', sheet_name='EmpInfo')

In [739]:
import pandas as pd
import numpy as np

In [740]:
df.head(7)

,Name,EmpID,Deptt,Passport
0,Sudeep,A342,Quality,DF453278
1,Ruchika,C578,Sales,CA567657
2,NaN,J436,Admin,DF453278
3,Arjun,A342,NaN,RF453432
4,Rishi,R475,Prodn,DF453278
5,Chetan,NaN,NaN,ER534867
6,Deepak,NaN,Quality,RF453432


In [741]:
ind = np.where(df.Deptt.isnull())

In [742]:
ind

(array([3, 5]),)

In [743]:
ind2 = np.where((df.EmpID.isnull()| df.Deptt.isnull()))

In [744]:
ind2

(array([3, 5, 6]),)

In [745]:
df1 = df.iloc[ind2[0]]

In [746]:
df1

,Name,EmpID,Deptt,Passport
3,Arjun,A342,NaN,RF453432
5,Chetan,NaN,NaN,ER534867
6,Deepak,NaN,Quality,RF453432


In [747]:
ind2 = not(np.where(df.EmpID.isnull()))

# where empid is not null

In [748]:
ind2

False

In [749]:
newdf = df.dropna()

In [750]:
newdf

,Name,EmpID,Deptt,Passport
0,Sudeep,A342,Quality,DF453278
1,Ruchika,C578,Sales,CA567657
4,Rishi,R475,Prodn,DF453278


In [751]:
df.isnull().sum()

Name        1
EmpID       2
Deptt       2
Passport    0
dtype: int64

In [752]:
df.Deptt.fillna('Overhead')

0     Quality
1       Sales
2       Admin
3    Overhead
4       Prodn
5    Overhead
6     Quality
Name: Deptt, dtype: object

In [753]:
df

,Name,EmpID,Deptt,Passport
0,Sudeep,A342,Quality,DF453278
1,Ruchika,C578,Sales,CA567657
2,NaN,J436,Admin,DF453278
3,Arjun,A342,NaN,RF453432
4,Rishi,R475,Prodn,DF453278
5,Chetan,NaN,NaN,ER534867
6,Deepak,NaN,Quality,RF453432


In [754]:
df['New Col'] = df.Deptt.fillna('Overhead')

In [755]:
df.Deptt.fillna('Overhead', inplace = True)

/var/folders/57/62f2rv1j4w94h8tfp_c43b1c0000gn/T/ipykernel_11842/969436898.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df.Deptt.fillna('Overhead', inplace = True)


In [756]:
# in case of numeric column,  nan is median values for that column

In [757]:
x1 = np.array([1,2,3,np.nan,5,np.nan,7])

In [758]:
df['Marks'] = x1

In [759]:
df

,Name,EmpID,Deptt,Passport,New Col,Marks
0,Sudeep,A342,Quality,DF453278,Quality,1.0
1,Ruchika,C578,Sales,CA567657,Sales,2.0
2,NaN,J436,Admin,DF453278,Admin,3.0
3,Arjun,A342,Overhead,RF453432,Overhead,NaN
4,Rishi,R475,Prodn,DF453278,Prodn,5.0
5,Chetan,NaN,Overhead,ER534867,Overhead,NaN
6,Deepak,NaN,Quality,RF453432,Quality,7.0


In [760]:
df['Marks'] = df.Marks.fillna(df.Marks.median())

In [761]:
df

,Name,EmpID,Deptt,Passport,New Col,Marks
0,Sudeep,A342,Quality,DF453278,Quality,1.0
1,Ruchika,C578,Sales,CA567657,Sales,2.0
2,NaN,J436,Admin,DF453278,Admin,3.0
3,Arjun,A342,Overhead,RF453432,Overhead,3.0
4,Rishi,R475,Prodn,DF453278,Prodn,5.0
5,Chetan,NaN,Overhead,ER534867,Overhead,3.0
6,Deepak,NaN,Quality,RF453432,Quality,7.0


In [762]:
df.Deptt.fillna(method='ffill')

/var/folders/57/62f2rv1j4w94h8tfp_c43b1c0000gn/T/ipykernel_11842/536854854.py:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.Deptt.fillna(method='ffill')


0     Quality
1       Sales
2       Admin
3    Overhead
4       Prodn
5    Overhead
6     Quality
Name: Deptt, dtype: object

In [763]:
df['Marks'] = df.Marks.fillna(df.Marks.mode())

In [764]:
df

,Name,EmpID,Deptt,Passport,New Col,Marks
0,Sudeep,A342,Quality,DF453278,Quality,1.0
1,Ruchika,C578,Sales,CA567657,Sales,2.0
2,NaN,J436,Admin,DF453278,Admin,3.0
3,Arjun,A342,Overhead,RF453432,Overhead,3.0
4,Rishi,R475,Prodn,DF453278,Prodn,5.0
5,Chetan,NaN,Overhead,ER534867,Overhead,3.0
6,Deepak,NaN,Quality,RF453432,Quality,7.0


In [765]:
df.head()

,Name,EmpID,Deptt,Passport,New Col,Marks
0,Sudeep,A342,Quality,DF453278,Quality,1.0
1,Ruchika,C578,Sales,CA567657,Sales,2.0
2,NaN,J436,Admin,DF453278,Admin,3.0
3,Arjun,A342,Overhead,RF453432,Overhead,3.0
4,Rishi,R475,Prodn,DF453278,Prodn,5.0


In [766]:
df

,Name,EmpID,Deptt,Passport,New Col,Marks
0,Sudeep,A342,Quality,DF453278,Quality,1.0
1,Ruchika,C578,Sales,CA567657,Sales,2.0
2,NaN,J436,Admin,DF453278,Admin,3.0
3,Arjun,A342,Overhead,RF453432,Overhead,3.0
4,Rishi,R475,Prodn,DF453278,Prodn,5.0
5,Chetan,NaN,Overhead,ER534867,Overhead,3.0
6,Deepak,NaN,Quality,RF453432,Quality,7.0


In [767]:
df.duplicated()

0    False
1    False
2    False
3    False
4    False
5    False
6    False
dtype: bool

In [768]:
df.tail()

,Name,EmpID,Deptt,Passport,New Col,Marks
2,NaN,J436,Admin,DF453278,Admin,3.0
3,Arjun,A342,Overhead,RF453432,Overhead,3.0
4,Rishi,R475,Prodn,DF453278,Prodn,5.0
5,Chetan,NaN,Overhead,ER534867,Overhead,3.0
6,Deepak,NaN,Quality,RF453432,Quality,7.0


In [769]:
df.duplicated('Passport')

0    False
1    False
2     True
3    False
4     True
5    False
6     True
dtype: bool

In [770]:
i= np.where(df.duplicated('Passport'))

In [771]:
i

(array([2, 4, 6]),)

In [772]:
df = df.iloc[i]

In [773]:
df

,Name,EmpID,Deptt,Passport,New Col,Marks
2,NaN,J436,Admin,DF453278,Admin,3.0
4,Rishi,R475,Prodn,DF453278,Prodn,5.0
6,Deepak,NaN,Quality,RF453432,Quality,7.0


In [774]:
np.where(df.Passport.duplicated(keep=False))

(array([0, 1]),)

In [775]:
np.where(df.Passport.duplicated(keep='first')) # except first

(array([1]),)

In [776]:
np.where(df.Passport.duplicated(keep='last')) # except last

(array([0]),)

---

In [777]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3 entries, 2 to 6
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Name      2 non-null      object 
 1   EmpID     2 non-null      object 
 2   Deptt     3 non-null      object 
 3   Passport  3 non-null      object 
 4   New Col   3 non-null      object 
 5   Marks     3 non-null      float64
dtypes: float64(1), object(5)
memory usage: 168.0+ bytes


In [778]:
df.shape

(3, 6)

In [779]:
df.columns

Index(['Name', 'EmpID', 'Deptt', 'Passport', 'New Col', 'Marks'], dtype='object')

In [780]:
df.index

Index([2, 4, 6], dtype='int64')

In [781]:
df['Name']

2       NaN
4     Rishi
6    Deepak
Name: Name, dtype: object

In [ ]:
df[['Name', 'Marks']]

,Name,Marks
2,NaN,3.0
4,Rishi,5.0
6,Deepak,7.0


In [783]:
df.iloc[1:5]

,Name,EmpID,Deptt,Passport,New Col,Marks
4,Rishi,R475,Prodn,DF453278,Prodn,5.0
6,Deepak,NaN,Quality,RF453432,Quality,7.0


In [784]:
df

,Name,EmpID,Deptt,Passport,New Col,Marks
2,NaN,J436,Admin,DF453278,Admin,3.0
4,Rishi,R475,Prodn,DF453278,Prodn,5.0
6,Deepak,NaN,Quality,RF453432,Quality,7.0


In [785]:
df[df['Marks']>1]

,Name,EmpID,Deptt,Passport,New Col,Marks
2,NaN,J436,Admin,DF453278,Admin,3.0
4,Rishi,R475,Prodn,DF453278,Prodn,5.0
6,Deepak,NaN,Quality,RF453432,Quality,7.0
