In [2]:
from sklearn.ensemble import AdaBoostClassifier
from sklearn.ensemble import AdaBoostRegressor
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.ensemble import GradientBoostingClassifier
%pip install xgboost
import xgboost
from xgboost import XGBRegressor
from xgboost import XGBClassifier
import os

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.2/2.2 MB 18.5 MB/s  0:00:00
Note: you may need to restart the kernel to use updated packages.


In [3]:
os.chdir(r'/Users/proxim/Desktop/CDAC-DBDA-coursework/08.advanced-analytics-stats')

In [6]:
import pandas as pd

In [10]:
df = pd.read_excel('data/SalesData.xlsx')

reg_dummy = pd.get_dummies(df.Region, drop_first=True).astype(int)
df.drop('Region', axis=1, inplace=True)
df = pd.concat([df,reg_dummy], axis=1)



In [11]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(df.drop('Sales',axis=1), df.Sales, random_state=10, test_size=0.1)

In [12]:
import numpy as np

In [14]:
import pandas as pd

In [17]:
#inverse relationship between learning rate and n_estimators

In [18]:
xgb_model = XGBRegressor(n_estimators=1000, learning_rate=0.01)
xgb_model.fit(x_train, y_train)
y_pred = xgb_model.predict(x_test)
rmse = np.sqrt(np.mean((y_test - y_pred)**2))
print("RMSE: %f" % (rmse))
#RMSE: 1033.211456



RMSE: 37.245680


In [19]:
gbr = GradientBoostingRegressor()
gbr.fit(x_train,y_train)
print(gbr.score(x_train, y_train))
print(gbr.score(x_test, y_test))

0.9239078292297334
0.8485120971819999


In [20]:
my_params={
    'loss':['squared_error', 'absolute_error','huber'],
    'learning_rate': [0.001,0.005,0.01],#,0.03,0.05,0.10,0.2],
    'n_estimators' : [10,30],#,50,100],
    #'criterion': ['friedman_mse', 'squared_error'],
    'max_depth':[2,3,4,5],
    #'min_samples_split' : [2,3,4,5],
    #'min_samples_leaf' : [2,3,4,5]
}

from sklearn.model_selection import GridSearchCV

grid=GridSearchCV(gbr,param_grid=my_params,cv=5,scoring='accuracy')
grid.fit(x_train,y_train)
grid.best_params_

/opt/homebrew/Caskroom/miniconda/base/lib/python3.13/site-packages/sklearn/model_selection/_validation.py:953: UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: 
Traceback (most recent call last):
  File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.13/site-packages/sklearn/model_selection/_validation.py", line 942, in _score
    scores = scorer(estimator, X_test, y_test, **score_params)
  File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.13/site-packages/sklearn/metrics/_scorer.py", line 308, in __call__
    return self._score(partial(_cached_call, None), estimator, X, y_true, **_kwargs)
           ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.13/site-packages/sklearn/metrics/_scorer.py", line 408, in _score
    return self._sign * self._score_func(y_true, y_pred, **scoring_kwargs)
                        ~~~~~~~~~~~~~~~~^

{'learning_rate': 0.001,
 'loss': 'squared_error',
 'max_depth': 2,
 'n_estimators': 10}

In [21]:
xgb = XGBRegressor()
mod1 = xgb.fit(x_train, y_train)
print(xgb.score(x_train, y_train))
print(xgb.score(x_test, y_test))

xgb = XGBRegressor(learning_rate=0.01, reg_lambda=1, reg_alpha=0.5,gamma=2,max_depth=3)
mod1 = xgb.fit(x_train, y_train)
print(xgb.score(x_train, y_train))
print(xgb.score(x_test, y_test))

0.9927439037092585
0.8087180591352026
0.7513936093088383
0.7394110835059649


In [22]:
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB()
model = gnb.fit(x_train, y_train)
print(gnb.score(x_train, y_train))
print(gnb.score(x_test, y_test)) 

ValueError: Unknown label type: (array([ 54.68182872,  75.20425428,  89.02672168, ..., 538.57637875,
       539.67508257, 552.5965262 ], shape=(1350,)),)

In [23]:
from sklearn.ensemble import AdaBoostRegressor
abr = AdaBoostRegressor(n_estimators=20, learning_rate=0.05, loss='linear')
mod1 = abr.fit(x_train, y_train)
print(abr.score(x_train, y_train))
print(abr.score(x_test, y_test))

0.8607760148105507
0.8233031382481543


In [24]:
df = pd.read_excel('CDAC_DataBook.xlsx', sheet_name='iris')
x_train, x_test, y_train, y_test = train_test_split(df.drop('Species', axis=1), df.Species, test_size=0.2, random_state=20)
from sklearn.naive_bayes import GaussianNB
mod1 = GaussianNB().fit(x_train,y_train)

FileNotFoundError: [Errno 2] No such file or directory: 'CDAC_DataBook.xlsx'

In [25]:
df = pd.read_excel('data/CDAC_DataBook.xlsx', sheet_name='iris')
x_train, x_test, y_train, y_test = train_test_split(df.drop('Species', axis=1), df.Species, test_size=0.2, random_state=20)

In [26]:
from sklearn.naive_bayes import GaussianNB
mod1 = GaussianNB().fit(x_train,y_train)

from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
y_pred_train = mod1.predict(x_train)
print(confusion_matrix(y_train,y_pred_train))
print(classification_report(y_train,y_pred_train))

[[42  0  0]
 [ 0 36  3]
 [ 0  2 37]]
                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        42
Iris-versicolor       0.95      0.92      0.94        39
 Iris-virginica       0.93      0.95      0.94        39

       accuracy                           0.96       120
      macro avg       0.96      0.96      0.96       120
   weighted avg       0.96      0.96      0.96       120



In [27]:
42/42+36

37.0

In [28]:
df.drop('Unnamed: 0', axis=1, inplace=True)

KeyError: "['Unnamed: 0'] not found in axis"

In [29]:
df.head()

,Sepal_length,Sepal_width,Petal_length,Petal_width,Species
0,5.1,3.5,1.4,0.2,Iris-setosa
1,4.9,3.0,1.4,0.2,Iris-setosa
2,4.7,3.2,1.3,0.2,Iris-setosa
3,4.6,3.1,1.5,0.2,Iris-setosa
4,5.0,3.6,1.4,0.2,Iris-setosa


In [31]:
df = pd.read_excel('data/PurchasePattern.xlsx')

In [33]:
df.drop('Unnamed: 0', axis=1, inplace=True)

In [34]:
df.head()

,CustomerSegment,Payment,Device,Region,Buy
0,Student,UPI,Laptop,Urban,Yes
1,Professional,Cash,Mobile,Urban,No
2,Student,UPI,Mobile,Urban,Yes
3,Professional,Cash,Mobile,Urban,No
4,Professional,Card,Laptop,Urban,Yes


In [36]:
np.unique(df.CustomerSegment)

array(['Homemaker', 'Professional', 'Retired', 'Student'], dtype=object)

In [37]:
np.unique(df.Payment)

array(['Card', 'Cash', 'UPI'], dtype=object)

In [39]:
np.unique(df.Device)

array(['Laptop', 'Mobile'], dtype=object)

In [40]:
np.unique(df.Device)

array(['Laptop', 'Mobile'], dtype=object)

In [41]:
np.unique(df.Region)

array(['Rural', 'Urban'], dtype=object)